
## A short introduction

1. More and more data...
    - Collecting, Analyzing and Interpreting data ?
  
 2. Statistical reasonning
    - Is now a fondamental part of experimental science 

   
  
  

## Studying a population

1. One often make statements like:
    - this gene is downregulated in lung cancer
    - in France the price of 1 kg of apple rised by 5 cents last year 
    - 99\% of the seeds in these bags are viable

2. In most of these cases
    - the population we are (implicitly) taking about is very large
    - collecting data is time consumming, costly and possibly it destroys the object
    - our measurements are inherently noisy





## Studying a population (inference)

Hence the data we collect on this population are not "perfect".
  
  - How can we make statements about the whole population ?
  - We need assumptions about the way data point were collected
  - Those assumptions should be known and explicit
  - These assumptions are formulated mathematically as a model
  
  - Draw a schematic representation of this...




## Undestanding statistical reasonning (1)

1. Cooking recipe level
 
    - if the data is such and such do this and this...
    - apply the code instructions of a vignette/tutorial online

2. **Applied statistics** level
  
    - understand statistical models and how to assess whether a method is valid (or not) to infer a model
    - this is doable using mostly highschool mathematics and a bit of R coding
  

## Undestanding statistical reasonning (2)

3. **Apprentice statistician** level

    - understand mathematical and algorithmic techniques behind statistical methods
    - this is doable for simple models using highschool mathematics and basic algorithmics
    - this doable for slightly more complex models with the help of a statistician
   
4. Master statistician level
